// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseBaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseBaseLoadingIcon: typeof import('./src/components/base/BaseLoadingIcon.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseLoadingIcon: typeof import('./src/components/base/BaseLoadingIcon.vue')['default']
  }
}

export { }
